config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users do
    resources :followers
  end

  resources :followers, only: [:destroy]

  get "dashboard", to: "pages#dashboard", as: "dashboard"
  get "feed", to: "pages#feed", as: "feed"

  resources :songs

  resources :playlists do
    resources :items
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  has_many :items, dependent: :delete_all
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_one_attached :mp3

  validates :cover, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def create
    @follow = Follower.create(follower_params)
    @user = User.find(params[:user_id])

    @follow.follow = @user.id
    @follow.user_id = current_user.id

    if @follow.save
      redirect_to user_path(@user), notice: "you are following: #{@user.username}"
    else
      flash[:alert] = 'something wrong happened :('
    end
  end

  def destroy
    @follow = Follower.find(params[:id])
    @follow.destroy

    redirect_to request.referrer, notice: "you are not following this artist anymore"
  end

  private

  def follower_params
    params.require(:follower).permit(:user_id, :follow)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.playlist = Playlist.find(params[:item][:playlist_id])
    @item.song = Song.find(params[:item][:song_id])


    if @item.save
      redirect_to playlist_path(@item.playlist), notice: "#{@item.song.title} was sucessfully added to #{@item.playlist.name} :)"
    else
      redirect_to root_path, status: :unprocessable_entity, notice: 'something went wrong :('
    end
  end

  private

  def item_params
    params.require(:item).permit(:playlist_id, :song_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @users = User.where(artist: true).sample(3)
    @songs = Song.all.sample(6)

    @artists = User.where(artist: true)
    @tracks = Song.all

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)
  end

  def dashboard
    @user = current_user
    @songs = Song.where(user_id: @user)

    @song_new = Song.new

    @top = @songs.sample(1)

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)

    @followers = Follower.where(follow: @user.id)


    @followers_last_week = period_filter(1.week.ago..Time.now)
    @followers_last_month = period_filter(1.month.ago..Time.now)
    @followers_last_year = period_filter(1.year.ago..Time.now)
  end

  def feed
    @feed = sort_feed

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)

  end

  private

  def period_filter(period)
    Follower.where(follow: @user.id, created_at: period)
  end

  def sort_feed
    feed = []

    Follower.where(user_id: current_user.id).each do |f|
      Song.where(user_id: f.follow).each do |s|
        feed << s
      end

      Playlist.where(user_id: f.follow).each do |p|
        feed << p
      end
    end

    return feed.sort_by(&:created_at).reverse
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
    @playlist_index = Playlist.all

    if params[:query].present?
      sql_subquery = <<~SQL
        playlists.name ILIKE :query
        OR users.username ILIKE :query
      SQL
      @playlist_index = @playlist_index.joins(:user).where(sql_subquery, query: "%#{params[:query]}%")
    end

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user

    if @playlist.save
      redirect_to playlist_path(@playlist), notice: 'playlist was sucessfully created :)'
    else
      redirect_to root_path, status: :unprocessable_entity, notice: 'playlist wasnt created :('
    end
  end

  def show
    @playlist_show = Playlist.find(params[:id])


    @item = Item.new

    @items = Item.where(playlist_id: @playlist_show)

    @songs = Song.all

    if params[:query].present?
      sql_subquery = <<~SQL
        songs.title ILIKE :query
        OR users.username ILIKE :query
      SQL
      @songs = @songs.joins(:user).where(sql_subquery, query: "%#{params[:query]}%")
    end

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)


  end

  def edit
    @playlist_edit = Playlist.find(params[:id])
    @user = User.find(@playlist_edit.user_id)

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)
  end

  def update
    @playlist_edit = Playlist.find(params[:id])
    @playlist_edit.update(playlist_params)

    redirect_to edit_playlist_path(@playlist_edit)
  end

  def destroy
    @playlist_edit = Playlist.find(params[:id])
    @playlist_edit.destroy

    redirect_to dashboard_path, status: :see_other
  end


  private

  def playlist_params
    params.require(:playlist).permit(:name, :photo)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
    @song = Song.find(params[:id])
    @user = User.find(@song.user_id)

    @songs = Song.where(user_id: @user).sample(3)
    @users = User.all.sample(3)

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)
  end

  def create
    @song_new = Song.new(song_params)
    @song_new.user = current_user

    if @song_new.save
      redirect_to song_path(@song_new), notice: "#{@song_new.title} was released :)"
    else
      flash[:alert] = 'something wrong happened :('
    end
  end

  def edit
    @song = Song.find(params[:id])
    @user = User.find(@song.user_id)

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)
  end

  def update
    @song = Song.find(params[:id])
    @song.update(song_params)

    redirect_to edit_song_path(@song)
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to dashboard_path, status: :see_other
  end

  private

  def song_params
    params.require(:song).permit(:title, :cover, :mp3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where(artist: true)

    if params[:query].present?
      @users = @users.where("username ILIKE ?", "%#{params[:query]}%")
    end

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)
  end

  def show
    @user = User.find(params[:id])
    @songs = Song.where(user_id: @user).take(3)

    @follower = Follower.new
    @followers = Follower.where(follow: @user.id)

    @followed = Follower.where(user_id: current_user.id, follow: @user.id).take(1)

    @sounds = Song.where(user_id: @user)

    @playlist = Playlist.new
    @playlists = Playlist.where(user_id: current_user)

    @playlists_user = Playlist.where(user_id: @user).take(3)

  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :pfp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSpotifyClone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= render "shared/sidebar" %>
    <%= render "shared/playlist_new" %>

    <%= yield %>
  </body>
</html>

app/views/pages/feed.html.erb
<div id="feed">
  <div class="container">
    <div class="header">
      <h1>Feed</h1>
      <p>Here's what's happening in the world:</p>
    </div>

    <div class="body">

      <% @feed.each do |item| %>
          <% if item.class == Song %>
            <%= link_to song_path(item) do%>
              <div class="post-card">
                <img src="<%= item.cover %>">

                <div class="post-info">
                  <h3><%= item.title %></h3>
                  <%= link_to item.user.username, user_path(item.user) %>
                  <p>Single, <%= time_ago_in_words(item.created_at) %> ago.</p>
                </div>

                <hr>
              </div>
            <% end %>

            <hr>
          <% else %>
            <%= link_to playlist_path(item) do %>
              <div class="post-card">
                <img src="<%= item.photo.url %>">

                <div class="post-info">
                  <h3><%= item.name %></h3>
                  <%= link_to item.user.username? ? item.user.username : "user" , user_path(item.user) %>
                  <p>Playlist, <%= time_ago_in_words(item.created_at) %> ago.</p>
                </div>
              </div>

            <% end %>

            <hr>
          <% end %>
      <% end %>

    </div>


  </div>
</div>

app/views/pages/home.html.erb
<div id="home">
  <div class="container">
    <% if user_signed_in? %>
      <div class="header">
        <% if Time.now.hour < 12 %>
            <h1>Good Morning</h1>
          <% else %>
            <h1> Good Afternoon </h1>
        <% end %>
        <p> Find <strong class="green"> <%= @tracks.size %> </strong> Songs made and released by <strong class="green"> <%= @artists.size %> </strong> Artists worldwide </p>
      </div>
    <% end %>

    <div class="section">
      <h2> Featured songs </h2>
      <% if user_signed_in? %>
        <h3> </h3>
      <% else %>
        <h3> want more sounds ? sign up now !</h3>
      <% end %>
      <div class="grid">
        <% @songs.each do |song| %>
          <%= link_to song_path(song) do %>
            <div class="card-songs" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= song.cover %>)">
              <%= song.title %>
            </div>
          <% end %>
        <% end %>

      </div>
    </div>

    <div class="section">
      <h2> Featured artists </h2>
      <% if user_signed_in? %>
        <h3> </h3>
      <% else %>
        <h3> want more creators ? sign up now !</h3>
      <% end %>
      <div class="grid">
        <% @users.each do |user| %>
          <%= link_to user_path(user) do %>
            <div class="card-artists" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= user.pfp %>)">
              <%= user.username %>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>

    <div class="section">
      <h2> Featured playlist </h2>
      <% if user_signed_in? %>
        <h3> </h3>
      <% else %>
        <h3> want more selections ? sign up now !</h3>
      <% end %>
      <div class="grid">
        <div class="card-playlist">
          <img src="https://upload.wikimedia.org/wikipedia/en/5/56/Joji_-_Smithereens.png" />
          <div class="card-playlist-infos">
            <h2>SMITHEREENS</h2>
            <p>Made and Published by <strong>Joji</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://i.scdn.co/image/ab67616d0000b2736fbac72609eca05f5d300c9f" />
          <div class="card-playlist-infos">
            <h2>Wake up & its Over</h2>
            <p>Made and Published by <strong>LoveJoy</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://media.mmorpg.com/images/heroes/news/52723.jpg"/>
          <div class="card-playlist-infos">
            <h2>Radical Summer</h2>
            <p>Made and Published by <strong>Monster Cat</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://m.media-amazon.com/images/I/71nrh7fjBJL._UF1000,1000_QL80_.jpg" />
          <div class="card-playlist-infos">
            <h2>Inside</h2>
            <p>Made and Published by <strong>Bo Burnham</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://mspoweruser.com/wp-content/uploads/2022/02/mca1.jpg" />
          <div class="card-playlist-infos">
            <h2>Minecraft soundTrack</h2>
            <p>Made and Published by <strong>C418</strong></p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://i.scdn.co/image/ab67616d0000b273c477f199067849f57f8a1f4e" />
          <div class="card-playlist-infos">
            <h2>in case I make it,</h2>
            <p>Made and Published by <strong>Will Wood</strong>.</p>
          </div>
        </div>
      </div>
    </div>

    <hr>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">


    <a href="" class="navbar-brand" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"><%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Spotify_icon.svg/1982px-Spotify_icon.svg.png" %></a>

    <% if user_signed_in? %>
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Artists", users_path, class: "nav-link navbar-btn" %>
        </li>

        <li class="nav-item">
          <%= link_to "Playlists", playlists_path, class: "nav-link navbar-btn" %>
        </li>

      </ul>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Feed", feed_path, class: "nav-link navbar-btn" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.pfp %>
              <%= image_tag "#{current_user.pfp}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <% else %>
              <%= image_tag "https://i.scdn.co/image/ab6761610000e5eb58efbed422ab46484466822b", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link navbar-btn" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_playlist_new.erb
<div id="playlist_new">

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Create Your Paylist</h1>
        </div>
        <%= simple_form_for @playlist do |f| %>
          <div class="modal-body">

                <%= f.error_notification %>
                <%= f.input :name,
                            required: true,
                            autofocus: true,
                            :placeholder => 'Title of your amazing playlist' %>

                <%= f.input :photo,
                            required: true,
                            as: :file,
                            :placeholder => 'a Cover for your amazing playlist'  %>
          </div>
          <div class="modal-footer">
            <button type="button" class="close-btn" data-bs-dismiss="modal">Close</button>
            <%= f.button :submit, value: 'Save', class: "save-btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_playlist_new.html.erb
<div id="modal-create">
  <div class="modal fade" id="playlist" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Create Your Paylist</h1>
        </div>
        <% if user_signed_in? %>
          <%= simple_form_for @playlist do |f| %>
            <div class="modal-body">

                  <%= f.error_notification %>
                  <%= f.input :name,
                              required: true,
                              autofocus: true,
                              :placeholder => 'Title of your amazing playlist',
                              input_html: {maxlength: 40, size: 100} %>

                  <%= f.input :photo,
                              required: true,
                              as: :file,
                              :placeholder => 'a Cover for your amazing playlist'  %>
            </div>
            <div class="modal-footer">
              <button type="button" class="close-btn" data-bs-dismiss="modal">Close</button>
              <%= f.button :submit, value: 'Save', class: "save-btn" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/songs/edit.html.erb
<div id="edit">
  <div class="container">
    <h2>Update details of <strong> <%= @song.title %> </strong>:</h2>
    <div class="form">
      <div class="container cover">
        <img src="<%= @song.cover %>" >

        <audio controls class="player">
          <source src="<%= @song.mp3.url %>">
        </audio>
      </div>


      <div class="container create-form">
        <%= simple_form_for @song do |f| %>
          <%= f.error_notification %>
          <%= f.input :title, :label => 'Song Title'%>
          <%= f.input :cover, :label => 'Cover Art'%>
          <%= f.input :mp3, :label => 'Song File', as: :file  %>


          <div class="form-btn">
            <%= f.button :submit, value: 'Save', class: "form-submit"%>

            <%= link_to "Delete", song_path(@song), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn form-delete"%>
          </div>
        <% end %>

      </div>

    </div>
  </div>

  <div class="container">
    <h2>Analytics:</h2>
    <div class="analytics">
      <div class="select">
        <i class="fa-solid fa-music"></i>
        <h2>Streams</h2>
        <h3> <strong> XXX </strong> </h3>
        <p> <strong> XXX </strong> in the Past Week </p>
      </div>

      <div class="center">
        <i class="fa-solid fa-list-ol"></i>
        <h2>In the Top</h2>
        <h3> <strong> XXX </strong> </h3>
        <p> tracks of the month </p>
      </div>

      <div class="select">
        <i class="fa-solid fa-play"></i>
        <h2>Streams</h2>
        <h3> <strong> XXX </strong> </h3>
        <p> <strong> XXX </strong> in the Past Week </p>
      </div>
    </div>
  </div>
</div>

app/views/songs/show.html.erb
<div id="song_show">
  <div class="container">
    <div class="body row">
      <div class="col">
        <img src="<%= @song.cover %>">
      </div>

      <div class="col">
        <h1><%= @song.title %></h1>
        <p><%= link_to "#{@user.username}", user_path(@user) %></p>

        <div class="player">
          <audio controls controlsList="nodownload">>
            <source src="<%= @song.mp3.url %>">
          </audio>
        </div>
      </div>
    </div>

      <hr>

    <div class="row">
        <div class="col grids">
          <h2>more sounds from <%= @user.username %>:</h2>

          <ul>
            <% @songs.each do |song| %>
              <li>
                <%= link_to song_path(song) do %>
                  <div class="card-playlist">
                    <img src= "<%= song.cover %>"/>
                    <div class="card-playlist-infos">
                      <h2><%= song.title %></h2>
                    </div>
                  </div>
                <% end %>
              </li>
                <hr>
            <% end %>
          </ul>

        </div>

        <div class="col grids">
          <h2><%= @user.username %> fans also like:</h2>
          <ul>
             <% @users.each do |user| %>
              <li>
                <%= link_to user_path(user) do %>
                  <div class="card-playlist">
                    <img src= "<%= user.pfp %>"/>
                    <div class="card-playlist-infos">
                      <h2><%= user.username %></h2>
                    </div>
                  </div>
                <% end %>
              </li>
                <hr>
            <% end %>
          </ul>
        </div>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div id="users">
  <div class="container">
    <div class="header">
      <h1> Artists all arround the world share their amazing songs on Spotify.</h1>

      <hr>
    </div>
  </div>

  <div class="search-bar">
      <h2> Lets find Your new favorite Artist </h2>
      <div class="bar">
        <%= form_with url: users_path, method: :get, class: "d-flex" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <% end %>
      </div>
  </div>

  <div class= "container">
    <div class="body">
        <div class="grid">
            <% @users.each do |user| %>
              <%= link_to user_path(user) do %>
                <div class="card-artists" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= user.pfp %>)">
                  <%= user.username %>

                  <div class="go-corner" href="#">
                    <div class="go-arrow">
                      →
                    </div>
                  </div>
                </div>

              <% end %>
            <% end %>
        </div>
    </div>
  </div>


  <div class="container">
      <hr>

    <div class="footer">
      <h1> Find playlists featuring your favorite artists </h1>

      <div class="grid">
        <div class="card-playlist">
          <img src="https://upload.wikimedia.org/wikipedia/en/5/56/Joji_-_Smithereens.png" />
          <div class="card-playlist-infos">
            <h2>SMITHEREENS</h2>
            <p>Made and Published by <strong>Joji</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://i.scdn.co/image/ab67616d0000b2736fbac72609eca05f5d300c9f" />
          <div class="card-playlist-infos">
            <h2>Wake up & its Over</h2>
            <p>Made and Published by <strong>LoveJoy</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://media.mmorpg.com/images/heroes/news/52723.jpg"/>
          <div class="card-playlist-infos">
            <h2>Radical Summer</h2>
            <p>Made and Published by <strong>Monster Cat</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://m.media-amazon.com/images/I/71nrh7fjBJL._UF1000,1000_QL80_.jpg" />
          <div class="card-playlist-infos">
            <h2>Inside</h2>
            <p>Made and Published by <strong>Bo Burnham</strong>.</p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://mspoweruser.com/wp-content/uploads/2022/02/mca1.jpg" />
          <div class="card-playlist-infos">
            <h2>Minecraft soundTrack</h2>
            <p>Made and Published by <strong>C418</strong></p>
          </div>
        </div>

        <div class="card-playlist">
          <img src="https://i.scdn.co/image/ab67616d0000b273c477f199067849f57f8a1f4e" />
          <div class="card-playlist-infos">
            <h2>in case I make it,</h2>
            <p>Made and Published by <strong>Will Wood</strong>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>